id <- c(1, 2, 3, 4, 5)
age <- c(34, 50, 29, 41, NA)
group <- c("control", "treatment", "control", "treatment", "control")
score <- c(7.2, 8.1, 6.9, 8.5, 7.0)

clinic <- data.frame(id = id, age = age, group = group, score = score)
print(clinic)
str(clinic)
summary(clinic)
print(clinic$age)
print(mean(clinic$age, na.rm = TRUE))
clinic$group <- factor(clinic$group, levels = c("control", "treatment"))
print(levels(clinic$group))
print(sum(is.na(clinic$age)))
